// packages/solid/src/widgets/FieldWidget.tsx
import { For, Match, Show, Switch, createMemo } from 'solid-js'
import type { FieldNode, UINode } from '@texaryn/core'
import { FieldErrors } from '../components/FieldErrors.js'
import { createFieldBinding } from '../field.js'

function sameJsonValue(left: unknown, right: unknown): boolean {
  if (left === right) return true
  if (typeof left !== 'object' || left === null || typeof right !== 'object' || right === null) return false
  if (Array.isArray(left) || Array.isArray(right)) {
    return Array.isArray(left) && Array.isArray(right) && left.length === right.length &&
      left.every((value, index) => sameJsonValue(value, right[index]))
  }

  const leftRecord = left as Record<string, unknown>
  const rightRecord = right as Record<string, unknown>
  const keys = Object.keys(leftRecord)
  return keys.length === Object.keys(rightRecord).length &&
    keys.every((key) => Object.hasOwn(rightRecord, key) && sameJsonValue(leftRecord[key], rightRecord[key]))
}

export function FieldWidget(props: { node: UINode }) {
  const field = createFieldBinding(() => props.node.id)
  const current = createMemo(() => field.node())
  const optionIndex = createMemo(() => {
    const options = current()?.enumValues ?? []
    const selected = field.value()
    return String(options.findIndex((option) => sameJsonValue(option.value, selected)))
  })
  const inputProps = () => ({
    id: field.inputId(),
    name: current()?.dataPointer || current()?.id || '',
    disabled: field.disabled() || Boolean(current()?.disabled),
    'aria-required': Boolean(current()?.constraints.required),
    'aria-invalid': field.invalid() || undefined,
    'aria-describedby': field.describedBy(),
    placeholder: current()?.placeholder,
  })
  const onTextInput = (event: InputEvent & { currentTarget: HTMLInputElement | HTMLTextAreaElement }) => {
    field.setRaw(event.currentTarget.value)
  }

  return (
    <Show when={field.visible() && current()}>
      {(node) => <div>
        <label for={field.inputId()}>
          {field.label()}
          <Show when={node().constraints.required}><span> (required)</span></Show>
        </label>
        <Switch>
          <Match when={node().enumValues?.length}>
            <select
              {...inputProps()}
              value={optionIndex()}
              aria-readonly={node().readOnly ? 'true' : undefined}
              onChange={(event) => {
                if (node().readOnly) {
                  event.currentTarget.value = optionIndex()
                  return
                }
                field.setRaw('', event.currentTarget.value)
              }}
              onBlur={field.onBlur}
            >
              <For each={node().enumValues}>{(option, index) => (
                <option value={String(index())}>{option.title ?? String(option.value)}</option>
              )}</For>
            </select>
          </Match>
          <Match when={node().fieldType === 'boolean'}>
            <input
              {...inputProps()}
              type="checkbox"
              checked={Boolean(field.value())}
              aria-readonly={node().readOnly ? 'true' : undefined}
              onChange={(event) => {
                if (node().readOnly) {
                  event.currentTarget.checked = Boolean(field.value())
                  return
                }
                field.setValue(event.currentTarget.checked)
              }}
              onBlur={field.onBlur}
            />
          </Match>
          <Match when={node().widget === 'textarea'}>
            <textarea
              {...inputProps()}
              value={field.display()}
              readOnly={node().readOnly}
              onInput={onTextInput}
              onBlur={field.onBlur}
            />
          </Match>
          <Match when={true}>
            <input
              {...inputProps()}
              type={node().fieldType === 'number' || node().fieldType === 'integer' ? 'number' : 'text'}
              value={field.display()}
              readOnly={node().readOnly}
              onInput={onTextInput}
              onBlur={field.onBlur}
            />
          </Match>
        </Switch>
        <Show when={field.description()}>
          <div id={field.descriptionId()}>{field.description()}</div>
        </Show>
        <FieldErrors id={field.errorId()} errors={field.visibleErrors()} />
      </div>}
    </Show>
  )
}

// packages/svelte/src/lib/components/FieldWidget.svelte
<script lang="ts">
  import { writable } from 'svelte/store'
  import type { FieldNode, UINode } from '@texaryn/core'
  import { useFormContext } from '../context.js'
  import { createFieldBinding, sameEnumValue } from '../field.js'
  import FieldErrors from './FieldErrors.svelte'

  export let node: UINode

  const context = useFormContext()
  const nodeId = writable(node.id)
  $: nodeId.set(node.id)

  const field = createFieldBinding(context.form, nodeId, context.idPrefix, context.messages)
  const {
    node: fieldNode,
    value,
    visibleErrors,
    display,
    label,
    description,
    labelFor,
    descriptionId,
    errorId,
    aria,
    messages,
  } = field

  $: enumOptions = ($fieldNode?.enumValues ?? []).map((entry, index) => ({
    token: String(index),
    value: entry.value,
    title: entry.title ?? String(entry.value),
  }))
  $: selectedToken = enumOptions.find((option) => sameEnumValue(option.value, $value))?.token ?? ''

  function handleInput(event: Event): void {
    field.setRaw((event.currentTarget as HTMLInputElement | HTMLTextAreaElement).value)
  }

  function handleSelect(event: Event): void {
    const select = event.currentTarget as HTMLSelectElement
    if ($fieldNode?.readOnly) {
      select.value = selectedToken
      return
    }
    field.setRaw(select.value, select.value)
  }

  function handleCheckbox(event: Event): void {
    const checkbox = event.currentTarget as HTMLInputElement
    if ($fieldNode?.readOnly) {
      checkbox.checked = Boolean($value)
      return
    }
    field.setValue(checkbox.checked)
  }

  function handleBlur(): void {
    field.onBlur()
  }
</script>

{#if $fieldNode && $aria}
  <div>
    <label for={$labelFor}>
      {#if $aria['aria-required'] && $messages.requiredIndicator().placement === 'before'}
        {@const indicator = $messages.requiredIndicator()}
        <span aria-hidden="true">{indicator.text} </span>
      {/if}
      {$label}
      {#if $aria['aria-required'] && $messages.requiredIndicator().placement === 'after'}
        {@const indicator = $messages.requiredIndicator()}
        <span aria-hidden="true"> {indicator.text}</span>
      {/if}
    </label>

    {#if $fieldNode.enumValues != null && $fieldNode.enumValues.length > 0}
      <select {...$aria} value={selectedToken} on:change={handleSelect} on:blur={handleBlur}>
        <option value=""></option>
        {#each enumOptions as option (option.token)}
          <option value={option.token}>{option.title}</option>
        {/each}
      </select>
    {:else if $fieldNode.fieldType === 'boolean'}
      <input
        {...$aria}
        type="checkbox"
        checked={Boolean($value)}
        on:change={handleCheckbox}
        on:blur={handleBlur}
      />
    {:else if $fieldNode.widget === 'textarea'}
      <textarea {...$aria} value={$display} on:input={handleInput} on:blur={handleBlur}></textarea>
    {:else}
      <input
        {...$aria}
        type={$fieldNode.fieldType === 'number' || $fieldNode.fieldType === 'integer' ? 'number' : 'text'}
        value={$display}
        on:input={handleInput}
        on:blur={handleBlur}
      />
    {/if}

    {#if $description}
      <div id={$descriptionId}>{$description}</div>
    {/if}
    <FieldErrors id={$errorId} errors={$visibleErrors} />
  </div>
{/if}
