// packages/solid/src/widgets/ObjectLayout.tsx
import { For, Show, createMemo } from 'solid-js'
import { objectChildKey } from '@texaryn/core'
import type { ContainerNode, ProjectionBoundaryTarget, UINode } from '@texaryn/core'
import { NodeRenderer } from '../components/NodeRenderer.js'
import { useFormContext } from '../context.js'

export function ObjectLayout(props: { node: UINode }) {
  const context = useFormContext()
  const container = createMemo(() => (context.document().nodes[props.node.id] ?? props.node) as ContainerNode)
  const children = createMemo(() => container().children
    .map((id) => context.document().nodes[id])
    .filter((child): child is UINode => child != null))
  const childKeys = createMemo(() => children().map(objectChildKey))
  const title = createMemo(() => container().annotations.title)
  const actions = createMemo(() => {
    const byReason = new Map<string, NonNullable<ContainerNode['boundaryTargets']>[number]>()
    for (const target of container().boundaryTargets ?? []) {
      if (!byReason.has(target.reason)) byReason.set(target.reason, target)
    }
    return [...byReason.values()]
  })
  const expandMessage = (target: ProjectionBoundaryTarget) => {
    const makeMessage = context.messages().expandBoundary ?? ((args) => ({
      label: `Show ${args.boundary}`,
      accessibleName: `Show ${args.boundary}`,
    }))
    return makeMessage({ boundary: target.reason, containerTitle: title(), position: 1, count: 1 })
  }
  const expand = (target: NonNullable<ContainerNode['boundaryTargets']>[number]) => {
    context.form().dispatch({ type: 'ExpandBoundary', containerId: container().id, targetToken: target.token })
  }
  const content = () => <div>
    <For each={childKeys()}>{(key) => {
      const child = createMemo(() => children().find((candidate) => objectChildKey(candidate) === key))
      return <Show when={child()}>{(value) => <NodeRenderer node={value()} />}</Show>
    }}</For>
    <For each={actions()}>{(target) => {
      const message = expandMessage(target)
      return <button type="button" aria-label={message.accessibleName} onClick={() => expand(target)}>{message.label}</button>
    }}</For>
  </div>

  return props.node.parentId === null
    ? content()
    : <fieldset role={title() === undefined ? 'none' : undefined}>
        <Show when={title()}>{(value) => <legend>{value()}</legend>}</Show>
        {content()}
      </fieldset>
}

// packages/svelte/src/lib/components/ObjectLayout.svelte
<script lang="ts">
  import { objectChildKey } from '@texaryn/core'
  import type { ContainerNode, UINode } from '@texaryn/core'
  import { englishMessages } from '@texaryn/core'
  import { useFormContext } from '../context.js'
  import NodeRenderer from './NodeRenderer.svelte'

  interface Props {
    node: UINode
  }

  let { node }: Props = $props()
  const context = useFormContext()
  const document = context.form.document
  const messages = context.messages
  const current = $derived(($document.nodes[node.id] ?? node) as ContainerNode)
  const nested = $derived(node.parentId !== null)
  const title = $derived(current.annotations.title)
  const children = $derived(
    current.children
      .map((id) => $document.nodes[id])
      .filter((child): child is UINode => child != null),
  )
  const actions = $derived(firstTargets(current.boundaryTargets ?? []))

  function firstTargets(targets: NonNullable<ContainerNode['boundaryTargets']>) {
    const byReason = new Map<string, (typeof targets)[number]>()
    for (const target of targets) {
      if (!byReason.has(target.reason)) byReason.set(target.reason, target)
    }
    return [...byReason.values()]
  }

  function expand(target: (typeof actions)[number]): void {
    context.form.dispatch({
      type: 'ExpandBoundary',
      containerId: current.id,
      targetToken: target.token,
    })
  }

  function expandMessage(target: (typeof actions)[number]) {
    const makeMessage = $messages.expandBoundary ?? englishMessages.expandBoundary!
    return makeMessage({
      boundary: target.reason,
      containerTitle: title,
      position: 1,
      count: 1,
    })
  }
</script>

{#snippet renderedChildren()}
  {#each children as child (objectChildKey(child))}
    <NodeRenderer node={child} />
  {/each}
  {#each actions as target (target.reason)}
    {@const message = expandMessage(target)}
    <button type="button" aria-label={message.accessibleName} onclick={() => expand(target)}>
      {message.label}
    </button>
  {/each}
{/snippet}

{#if nested}
  <fieldset role={title === undefined ? 'none' : undefined}>
    {#if title !== undefined}<legend>{title}</legend>{/if}
    <div>{@render renderedChildren()}</div>
  </fieldset>
{:else}
  <div>{@render renderedChildren()}</div>
{/if}
