// packages/solid/src/context.tsx
import { createContext, useContext } from 'solid-js'
import type { Accessor } from 'solid-js'
import type { FormMessages, FormRuntime, RendererRegistry, UIDocument } from '@texaryn/core'
import type { WidgetComponent } from './widget.js'

export interface SolidFormContext {
  form: Accessor<FormRuntime>
  document: Accessor<UIDocument>
  registry: Accessor<RendererRegistry<WidgetComponent>>
  messages: Accessor<FormMessages>
  idPrefix: Accessor<string>
}

export const FormContext = createContext<SolidFormContext>()

export function useFormContext(): SolidFormContext {
  const context = useContext(FormContext)
  if (!context) throw new Error('Solid form widgets must be rendered below FormRoot')
  return context
}

// packages/angular/src/context.ts
import { inject, InjectionToken } from '@angular/core'
import type { Signal } from '@angular/core'
import type { FormMessages, RendererRegistry } from '@texaryn/core'
import type { AngularForm } from './form.js'
import type { WidgetComponent } from './widget.js'

export interface FormContext {
  readonly form: Signal<AngularForm>
  readonly registry: Signal<RendererRegistry<WidgetComponent>>
  readonly messages: Signal<FormMessages | undefined>
  readonly idPrefix: Signal<string>
}

export const FORM_CONTEXT = new InjectionToken<FormContext>('texaryn.angular.form-context')

export function useFormContext(): FormContext {
  return inject(FORM_CONTEXT)
}
