// packages/angular/src/widgets/object-layout.ts
import { NgTemplateOutlet } from '@angular/common'
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core'
import { englishMessages, objectChildKey } from '@texaryn/core'
import type { ContainerNode, UINode } from '@texaryn/core'
import { useFormContext } from '../context.js'
import { NodeRenderer } from '../components/node-renderer.js'

@Component({
  selector: 'texaryn-object-layout',
  standalone: true,
  imports: [NgTemplateOutlet, NodeRenderer],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let current = currentNode();
    @if (current.parentId === null) {
      <div>
        <ng-container *ngTemplateOutlet="content" />
      </div>
    } @else {
      <fieldset [attr.role]="current.annotations.title === undefined ? 'none' : null">
        @if (current.annotations.title !== undefined) {
          <legend>{{ current.annotations.title }}</legend>
        }
        <div>
          <ng-container *ngTemplateOutlet="content" />
        </div>
      </fieldset>
    }
    <ng-template #content>
      @for (child of children(); track childKey(child)) {
        <texaryn-node-renderer [node]="child" />
      }
      @for (action of expandActions(); track action.target.reason) {
        <button
          type="button"
          [attr.aria-label]="action.message.accessibleName"
          (click)="expand(action.target.token)"
        >{{ action.message.label }}</button>
      }
    </ng-template>
  `,
})
export class ObjectLayout {
  readonly node = input.required<UINode>()
  private readonly context = useFormContext()
  readonly currentNode = computed(() => {
    const node = this.node() as ContainerNode
    return (this.context.form().document().nodes[node.id] ?? node) as ContainerNode
  })
  readonly children = computed(() => {
    const document = this.context.form().document()
    return this.currentNode().children
      .map((id) => document.nodes[id])
      .filter((child): child is UINode => child !== undefined)
  })
  readonly expandActions = computed(() => {
    const current = this.currentNode()
    const messages = this.context.messages() ?? englishMessages
    const firstByReason = new Map<string, NonNullable<ContainerNode['boundaryTargets']>[number]>()
    for (const target of current.boundaryTargets ?? []) {
      if (!firstByReason.has(target.reason)) firstByReason.set(target.reason, target)
    }
    return [...firstByReason.values()].map((target) => ({
      target,
      message: (messages.expandBoundary ?? englishMessages.expandBoundary!)({
        boundary: target.reason,
        containerTitle: current.annotations.title,
        position: 1,
        count: 1,
      }),
    }))
  })
  readonly childKey = objectChildKey

  expand(targetToken: string): void {
    this.context.form().dispatch({
      type: 'ExpandBoundary',
      containerId: this.currentNode().id,
      targetToken,
    })
  }
}

// packages/solid/src/widgets/ObjectLayout.tsx
import { For, Show, createMemo } from 'solid-js'
import { objectChildKey } from '@texaryn/core'
import type { ContainerNode, ProjectionBoundaryTarget, UINode } from '@texaryn/core'
import { NodeRenderer } from '../components/NodeRenderer.js'
import { useFormContext } from '../context.js'

export function ObjectLayout(props: { node: UINode }) {
  const context = useFormContext()
  const container = createMemo(() => (context.document().nodes[props.node.id] ?? props.node) as ContainerNode)
  const children = createMemo(() => container().children
    .map((id) => context.document().nodes[id])
    .filter((child): child is UINode => child != null))
  const childKeys = createMemo(() => children().map(objectChildKey))
  const title = createMemo(() => container().annotations.title)
  const actions = createMemo(() => {
    const byReason = new Map<string, NonNullable<ContainerNode['boundaryTargets']>[number]>()
    for (const target of container().boundaryTargets ?? []) {
      if (!byReason.has(target.reason)) byReason.set(target.reason, target)
    }
    return [...byReason.values()]
  })
  const expandMessage = (target: ProjectionBoundaryTarget) => {
    const makeMessage = context.messages().expandBoundary ?? ((args) => ({
      label: `Show ${args.boundary}`,
      accessibleName: `Show ${args.boundary}`,
    }))
    return makeMessage({ boundary: target.reason, containerTitle: title(), position: 1, count: 1 })
  }
  const expand = (target: NonNullable<ContainerNode['boundaryTargets']>[number]) => {
    context.form().dispatch({ type: 'ExpandBoundary', containerId: container().id, targetToken: target.token })
  }
  const content = () => <div>
    <For each={childKeys()}>{(key) => {
      const child = createMemo(() => children().find((candidate) => objectChildKey(candidate) === key))
      return <Show when={child()}>{(value) => <NodeRenderer node={value()} />}</Show>
    }}</For>
    <For each={actions()}>{(target) => {
      const message = expandMessage(target)
      return <button type="button" aria-label={message.accessibleName} onClick={() => expand(target)}>{message.label}</button>
    }}</For>
  </div>

  return props.node.parentId === null
    ? content()
    : <fieldset role={title() === undefined ? 'none' : undefined}>
        <Show when={title()}>{(value) => <legend>{value()}</legend>}</Show>
        {content()}
      </fieldset>
}
