// packages/react/src/widgets/ArrayControl.tsx
import React from 'react'
import type { ContainerNode, UINode } from '@texaryn/core'
import { useFieldArray } from '../hooks/use-field-array.js'
import { NodeRenderer } from '../components/NodeRenderer.js'
import { useRendererContext } from '../components/renderer-context.js'
import { useArrayActions } from '../hooks/use-array-actions.js'

export interface WidgetProps {
  node: UINode
}

function focusAfterRender(row: HTMLElement | null, direction: 'up' | 'down'): void {
  const focus = () => row?.querySelector<HTMLButtonElement>(`[data-reorder-direction="${direction}"]`)?.focus()
  if (typeof requestAnimationFrame === 'function') requestAnimationFrame(focus)
  else setTimeout(focus, 0)
}

function ArrayControlImpl({ node }: WidgetProps) {
  const containerNode = node as ContainerNode
  const fieldArray = useFieldArray(containerNode.id)
  const { document, registry } = useRendererContext()
  const actions = useArrayActions(node)

  return (
    <div>
      {fieldArray.items.map((item, index) => {
        const childNode = item.nodeId ? document.nodes[item.nodeId] : undefined
        const remove = actions.remove(index + 1, childNode)
        const moveUp = actions.moveUp(index + 1, childNode)
        const moveDown = actions.moveDown(index + 1, childNode)
        return (
          <div key={item.id} data-array-row="">
            {childNode ? (
              <NodeRenderer node={childNode} document={document} registry={registry} />
            ) : null}
            {fieldArray.canReorder && index > 0 ? (
              <button
                type="button"
                aria-label={moveUp.accessibleName}
                data-reorder-direction="up"
                onClick={(event) => {
                  const wasFocused = globalThis.document.activeElement === event.currentTarget
                  const row = event.currentTarget.closest<HTMLElement>('[data-array-row]')
                  fieldArray.move(index, index - 1)
                  if (wasFocused && index === 1) focusAfterRender(row, 'down')
                }}
              >
                {moveUp.label}
              </button>
            ) : null}
            {fieldArray.canReorder && index < fieldArray.items.length - 1 ? (
              <button
                type="button"
                aria-label={moveDown.accessibleName}
                data-reorder-direction="down"
                onClick={(event) => {
                  const wasFocused = globalThis.document.activeElement === event.currentTarget
                  const row = event.currentTarget.closest<HTMLElement>('[data-array-row]')
                  fieldArray.move(index, index + 1)
                  if (wasFocused && index === fieldArray.items.length - 2) focusAfterRender(row, 'up')
                }}
              >
                {moveDown.label}
              </button>
            ) : null}
            {fieldArray.canRemove ? (
              // The visible word stays short; the name that distinguishes the
              // row goes in aria-label, which contains it so speech input
              // still works.
              <button
                type="button"
                aria-label={remove.accessibleName}
                onClick={() => fieldArray.remove(index)}
              >
                {remove.label}
              </button>
            ) : null}
          </div>
        )
      })}
      {fieldArray.canAdd ? (
        <button type="button" aria-label={actions.add.accessibleName} onClick={() => fieldArray.add()}>
          {actions.add.label}
        </button>
      ) : null}
    </div>
  )
}

export const ArrayControl = React.memo(
  ArrayControlImpl,
  (prev, next) => prev.node.id === next.node.id,
)

// packages/angular/src/widgets/array-control.ts
import {
  afterNextRender,
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  Injector,
  input,
} from '@angular/core'
import type { ContainerNode, UINode } from '@texaryn/core'
import { englishMessages } from '@texaryn/core'
import { NodeRenderer } from '../components/node-renderer.js'
import { useFormContext } from '../context.js'
import { useFieldArray } from '../use-field-array.js'

@Component({
  selector: 'texaryn-array-control',
  standalone: true,
  imports: [NodeRenderer],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @for (item of array.items(); track item.id; let index = $index) {
      <div data-array-row>
        @if (item.nodeId; as childId) {
          @let child = context.form().document().nodes[childId];
          @if (child) {
            <texaryn-node-renderer [node]="child" />
          }
        }
        @if (array.canReorder() && index > 0) {
          @let action = messages().moveItemUp({
            position: index + 1,
            itemTitle: itemTitle(item.nodeId),
            containerTitle: currentArray().annotations.title,
          });
          <button
            type="button"
            data-reorder-direction="up"
            [attr.aria-label]="action.accessibleName"
            (click)="move($event, index, index - 1, 'down', index === 1)"
          >{{ action.label }}</button>
        }
        @if (array.canReorder() && index < array.items().length - 1) {
          @let action = messages().moveItemDown({
            position: index + 1,
            itemTitle: itemTitle(item.nodeId),
            containerTitle: currentArray().annotations.title,
          });
          <button
            type="button"
            data-reorder-direction="down"
            [attr.aria-label]="action.accessibleName"
            (click)="move($event, index, index + 1, 'up', index === array.items().length - 2)"
          >{{ action.label }}</button>
        }
        @if (array.canRemove()) {
          @let action = messages().removeItem({
            position: index + 1,
            itemTitle: itemTitle(item.nodeId),
            containerTitle: currentArray().annotations.title,
          });
          <button type="button" [attr.aria-label]="action.accessibleName" (click)="array.remove(index)">
            {{ action.label }}
          </button>
        }
      </div>
    }
    @if (array.canAdd()) {
      @let action = messages().addItem({
        itemTemplateTitle: currentArray().arrayMeta?.itemTitle,
        containerTitle: currentArray().annotations.title,
      });
      <button type="button" [attr.aria-label]="action.accessibleName" (click)="array.add()">
        {{ action.label }}
      </button>
    }
  `,
})
export class ArrayControl {
  readonly node = input.required<UINode>()
  readonly context = useFormContext()
  readonly array = useFieldArray(() => this.node().id)
  readonly currentArray = computed(() => {
    const node = this.node() as ContainerNode
    return (this.context.form().document().nodes[node.id] ?? node) as ContainerNode
  })
  readonly messages = computed(() => this.context.messages() ?? englishMessages)
  private readonly injector = inject(Injector)

  itemTitle(nodeId: string | undefined): string | undefined {
    if (!nodeId) return undefined
    return this.context.form().document().nodes[nodeId]?.annotations.title
  }

  move(
    event: MouseEvent,
    from: number,
    to: number,
    nextDirection: 'up' | 'down',
    restoreAtBoundary: boolean,
  ): void {
    const button = event.currentTarget as HTMLButtonElement
    const wasFocused = button.ownerDocument.activeElement === button
    const row = button.closest<HTMLElement>('[data-array-row]')
    this.array.move(from, to)
    if (wasFocused && restoreAtBoundary) {
      afterNextRender({
        mixedReadWrite: () =>
          row?.querySelector<HTMLButtonElement>(`[data-reorder-direction="${nextDirection}"]`)?.focus(),
      }, { injector: this.injector })
    }
  }
}
