// packages/react/src/components/DocumentRoot.tsx
import { createContext, useContext } from 'react'
import type { ComponentType, ReactNode } from 'react'
import type {
  DocumentNode,
  DocumentRuntime,
  DocumentCollectionRow,
  RendererRegistry,
  UIDocumentV2,
} from '@texaryn/core'
import { useStore } from '../hooks/use-store.js'

export type DocumentWidgetComponent = ComponentType<{
  node: DocumentNode
  runtime: DocumentRuntime
}>

export interface DocumentRootProps {
  runtime: DocumentRuntime
  registry?: RendererRegistry<DocumentWidgetComponent, DocumentNode>
  onActionError?: (error: unknown) => void
}

interface DocumentContextValue {
  runtime: DocumentRuntime
  document: UIDocumentV2
  registry: RendererRegistry<DocumentWidgetComponent, DocumentNode> | undefined
  onActionError: (error: unknown) => void
}

const DocumentContext = createContext<DocumentContextValue | null>(null)

function useDocumentContext(): DocumentContextValue {
  const context = useContext(DocumentContext)
  if (!context) throw new Error('DocumentRoot must contain every display node')
  return context
}

function useRows(nodeId: DocumentNode['id']): readonly DocumentCollectionRow[] {
  const { runtime } = useDocumentContext()
  const store = runtime.getCollection(nodeId)
  if (!store) throw new Error(`Node ${nodeId} is not a collection`)
  return useStore(store)
}

function DisplayNodeView({ nodeId }: { nodeId: DocumentNode['id'] }): ReactNode {
  const { runtime, document, registry, onActionError } = useDocumentContext()
  const node = document.nodes[nodeId]
  if (!node) return null
  const Widget = registry?.resolve(node)
  if (Widget) return <Widget node={node} runtime={runtime} />

  if (node.type === 'container') {
    const children = node.children.map((childId) => <DisplayNodeView key={childId} nodeId={childId} />)
    if (node.containerType === 'group') {
      return <fieldset><legend>{node.annotations.title}</legend>{children}</fieldset>
    }
    return <div data-texaryn-layout="">{children}</div>
  }
  if (node.type === 'text') {
    if (node.textRole === 'heading') return <h2>{node.content}</h2>
    if (node.textRole === 'help') return <p role="note">{node.content}</p>
    return <p>{node.content}</p>
  }
  if (node.type === 'list') return <DisplayList node={node} />
  if (node.type === 'table') return <DisplayTable node={node} />
  if (node.type === 'action') {
    return (
      <button
        type="button"
        disabled={!runtime.hasActionHandler(node.actionType)}
        onClick={() => {
          void runtime.invokeAction(node.id).catch(onActionError)
        }}
      >
        {node.label}
      </button>
    )
  }
  return null
}

function DisplayList({ node }: { node: Extract<DocumentNode, { type: 'list' }> }) {
  const rows = useRows(node.id)
  return <ul>{rows.map((row) => <li key={row.id}>{row.value === null ? '' : String(row.value)}</li>)}</ul>
}

function DisplayTable({ node }: { node: Extract<DocumentNode, { type: 'table' }> }) {
  const rows = useRows(node.id)
  return (
    <table>
      <thead>
        <tr>{node.columns.map((column) => <th key={column.id} scope="col">{column.label}</th>)}</tr>
      </thead>
      <tbody>
        {rows.map((row) => (
          <tr key={row.id}>
            {node.columns.map((column, index) => {
              const value = row.cells[index] ?? null
              return <td key={column.id}>{value === null ? '' : String(value)}</td>
            })}
          </tr>
        ))}
      </tbody>
    </table>
  )
}

export function DocumentRoot({ runtime, registry, onActionError = console.error }: DocumentRootProps) {
  const document = useStore(runtime.document)
  const context: DocumentContextValue = { runtime, document, registry, onActionError }
  if (!document.nodes[document.rootId]) return null
  return (
    <DocumentContext.Provider value={context}>
      <DisplayNodeView nodeId={document.rootId} />
    </DocumentContext.Provider>
  )
}

// packages/solid/src/components/DocumentRoot.tsx
import { createContext, createMemo, For, Show, useContext } from 'solid-js'
import type { Accessor, Component, JSX } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import type {
  DisplayContainerNode,
  DisplayTextNode,
  DocumentCollectionRow,
  DocumentNode,
  DocumentRuntime,
  ListNode,
  RendererRegistry,
  TableNode,
  UIDocumentV2,
} from '@texaryn/core'
import type { NodeId } from '@texaryn/core'
import { useStore } from '../store.js'

export type DocumentWidgetComponent = Component<{ node: DocumentNode; runtime: DocumentRuntime }>

export interface DocumentRootProps {
  runtime: DocumentRuntime
  registry?: RendererRegistry<DocumentWidgetComponent, DocumentNode>
  onActionError?: (error: unknown) => void
  children?: JSX.Element
}

interface DocumentContextValue {
  runtime: Accessor<DocumentRuntime>
  document: Accessor<UIDocumentV2>
  registry: Accessor<RendererRegistry<DocumentWidgetComponent, DocumentNode> | undefined>
  onActionError: Accessor<((error: unknown) => void) | undefined>
}

const DocumentContext = createContext<DocumentContextValue>()

function useDocumentContext(): DocumentContextValue {
  const context = useContext(DocumentContext)
  if (!context) throw new Error('Display nodes must be rendered below DocumentRoot')
  return context
}

function useRows(nodeId: NodeId): Accessor<readonly DocumentCollectionRow[]> {
  const context = useDocumentContext()
  return useStore(() => {
    const store = context.runtime().getCollection(nodeId)
    if (!store) throw new Error(`Node ${nodeId} is not a collection`)
    return store
  })
}

function DisplayNodeView(props: { nodeId: NodeId }) {
  const context = useDocumentContext()
  const node = createMemo(() => context.document().nodes[props.nodeId])
  const kind = createMemo(() => {
    const current = node()
    if (!current) return undefined
    if (current.type === 'container') return `container:${current.containerType}`
    if (current.type === 'text') return `text:${current.textRole}`
    return current.type
  })
  const widget = createMemo(() => {
    const current = node()
    return current ? context.registry()?.resolve(current) : undefined
  })
  const container = (): DisplayContainerNode | undefined => {
    const current = node()
    return current?.type === 'container' ? current : undefined
  }
  const text = (): DisplayTextNode | undefined => {
    const current = node()
    return current?.type === 'text' ? current : undefined
  }
  const list = (): ListNode | undefined => {
    const current = node()
    return current?.type === 'list' ? current : undefined
  }
  const table = (): TableNode | undefined => {
    const current = node()
    return current?.type === 'table' ? current : undefined
  }
  const action = () => {
    const current = node()
    return current?.type === 'action' ? current : undefined
  }

  return (
    <Show when={kind()} keyed>
      {(selectedKind) => {
        let fallback: JSX.Element = null
        if (selectedKind.startsWith('container:')) {
          const children = () => container()?.children ?? []
          fallback = selectedKind === 'container:group'
            ? <fieldset><legend>{container()?.annotations.title}</legend><For each={children()}>{(childId) => <DisplayNodeView nodeId={childId} />}</For></fieldset>
            : <div data-texaryn-layout=""><For each={children()}>{(childId) => <DisplayNodeView nodeId={childId} />}</For></div>
        } else if (selectedKind === 'text:heading') {
          fallback = <h2>{text()?.content}</h2>
        } else if (selectedKind === 'text:help') {
          fallback = <p role="note">{text()?.content}</p>
        } else if (selectedKind === 'text:paragraph') {
          fallback = <p>{text()?.content}</p>
        } else if (selectedKind === 'list') {
          fallback = <Show when={list()}><DisplayList nodeId={props.nodeId} /></Show>
        } else if (selectedKind === 'table') {
          fallback = <Show when={table()}><DisplayTable nodeId={props.nodeId} /></Show>
        } else if (selectedKind === 'action') {
          fallback = (
            <button
              type="button"
              disabled={!context.runtime().hasActionHandler(action()?.actionType ?? '')}
              onClick={() => {
                const current = node()
                if (current?.type !== 'action') return
                void context.runtime().invokeAction(current.id).catch((error) => {
                  const onError = context.onActionError()
                  if (onError) onError(error)
                  else console.error(error)
                })
              }}
            >
              {action()?.label ?? ''}
            </button>
          )
        }

        return (
          <Show when={widget()} fallback={fallback}>
            <Dynamic component={widget()!} node={node()!} runtime={context.runtime()} />
          </Show>
        )
      }}
    </Show>
  )
}

function DisplayList(props: { nodeId: NodeId }) {
  const rows = useRows(props.nodeId)
  return (
    <ul>
      <For each={rows().map((row) => row.id)}>{(rowId) => {
        const row = () => rows().find((candidate) => candidate.id === rowId)
        return <li>{row()?.value == null ? '' : String(row()?.value)}</li>
      }}</For>
    </ul>
  )
}

function DisplayTable(props: { nodeId: NodeId }) {
  const context = useDocumentContext()
  const rows = useRows(props.nodeId)
  const node = createMemo(() => {
    const current = context.document().nodes[props.nodeId]
    return current?.type === 'table' ? current : undefined
  })
  return (
    <table>
      <thead><tr><For each={node()?.columns ?? []}>{(column) => <th scope="col">{column.label}</th>}</For></tr></thead>
      <tbody>
        <For each={rows().map((row) => row.id)}>{(rowId) => {
          const row = () => rows().find((candidate) => candidate.id === rowId)
          return (
          <tr>
            <For each={node()?.columns ?? []}>{(column, index) => {
              const value = () => row()?.cells[index()] ?? null
              return <td>{value() === null ? '' : String(value())}</td>
            }}</For>
          </tr>
          )
        }}</For>
      </tbody>
    </table>
  )
}

export function DocumentRoot(props: DocumentRootProps) {
  const document = useStore(() => props.runtime.document)
  const context: DocumentContextValue = {
    runtime: () => props.runtime,
    document,
    registry: () => props.registry,
    onActionError: () => props.onActionError,
  }

  return (
    <DocumentContext.Provider value={context}>
      <Show when={document().rootId} keyed>
        {(rootId) => <DisplayNodeView nodeId={rootId} />}
      </Show>
      {props.children}
    </DocumentContext.Provider>
  )
}
