// packages/react/src/context.ts
import { createContext, useContext } from 'react'
import type { FormRuntime } from '@texaryn/core'

export const FormContext = createContext<FormRuntime | null>(null)

export function useFormContext(): FormRuntime {
  const runtime = useContext(FormContext)
  if (!runtime) {
    throw new Error('useFormContext must be used within a FormProvider')
  }
  return runtime
}

// packages/solid/src/context.tsx
import { createContext, useContext } from 'solid-js'
import type { Accessor } from 'solid-js'
import type { FormMessages, FormRuntime, RendererRegistry, UIDocument } from '@texaryn/core'
import type { WidgetComponent } from './widget.js'

export interface SolidFormContext {
  form: Accessor<FormRuntime>
  document: Accessor<UIDocument>
  registry: Accessor<RendererRegistry<WidgetComponent>>
  messages: Accessor<FormMessages>
  idPrefix: Accessor<string>
}

export const FormContext = createContext<SolidFormContext>()

export function useFormContext(): SolidFormContext {
  const context = useContext(FormContext)
  if (!context) throw new Error('Solid form widgets must be rendered below FormRoot')
  return context
}
