// packages/svelte/src/lib/components/DocumentRoot.svelte
<script lang="ts">
  import type { DocumentNode, DocumentRuntime } from '@texaryn/core'
  import type { RendererRegistry } from '@texaryn/core'
  import type { DocumentWidgetComponent } from '../widget.js'
  import DocumentNodeView from './DocumentNode.svelte'

  interface Props {
    runtime: DocumentRuntime
    registry?: RendererRegistry<DocumentWidgetComponent, DocumentNode>
    onActionError?: (error: unknown) => void
    children?: import('svelte').Snippet
  }

  let { runtime, registry, onActionError, children }: Props = $props()
  let document = $state<import('@texaryn/core').UIDocumentV2 | undefined>()
  $effect(() => {
    const store = runtime.document
    document = store.getSnapshot()
    return store.subscribe(() => { document = store.getSnapshot() })
  })
</script>

{#if document?.nodes[document.rootId]}
  <DocumentNodeView
    nodeId={document.rootId}
    {runtime}
    {document}
    {registry}
    {onActionError}
  />
{/if}

{@render children?.()}

// packages/angular/src/components/document-root.ts
import { ChangeDetectionStrategy, Component, forwardRef, input } from '@angular/core'
import type { DocumentNode, DocumentRuntime, RendererRegistry, UIDocumentV2 } from '@texaryn/core'
import type { Signal, Type } from '@angular/core'
import type { NodeId } from '@texaryn/core'
import { useDynamicStore } from '../store.js'
import { DOCUMENT_CONTEXT } from '../document-context.js'
import type { AngularDocumentWidget } from '../widget.js'
import { DocumentNodeRenderer } from './document-node-renderer.js'

const emptyDocument: UIDocumentV2 = { version: 2, rootId: '' as NodeId, nodes: {} }

@Component({
  selector: 'texaryn-document-root',
  standalone: true,
  imports: [DocumentNodeRenderer],
  providers: [{ provide: DOCUMENT_CONTEXT, useExisting: forwardRef(() => DocumentRoot) }],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @let current = document();
    @if (current.nodes[current.rootId]) {
      <texaryn-document-node-renderer [nodeId]="current.rootId" />
    }
  `,
})
export class DocumentRoot {
  readonly runtime = input.required<DocumentRuntime>()
  readonly registry = input<RendererRegistry<Type<AngularDocumentWidget>, DocumentNode> | undefined>(undefined)
  readonly onActionError = input<((error: unknown) => void) | undefined>(undefined)
  readonly document: Signal<UIDocumentV2> = useDynamicStore(() => this.runtime().document, emptyDocument)
}
