// packages/angular/src/use-field-array.ts
import { computed } from '@angular/core'
import type { Signal } from '@angular/core'
import type { ContainerNode, NodeId, StableItemId } from '@texaryn/core'
import { useFormContext } from './context.js'

export interface FieldArrayItem {
  id: StableItemId
  nodeId: NodeId | undefined
}

export interface FieldArrayBinding {
  items: Signal<FieldArrayItem[]>
  canAdd: Signal<boolean>
  canRemove: Signal<boolean>
  canReorder: Signal<boolean>
  add(value?: unknown): void
  remove(index: number): void
  move(from: number, to: number): void
}

export function useFieldArray(nodeId: () => NodeId): FieldArrayBinding {
  const context = useFormContext()
  const form = computed(() => context.form())
  const container = computed(() => {
    const document = form().document()
    const node = document.nodes[nodeId()]
    return node?.type === 'container' && node.containerType === 'array'
      ? node as ContainerNode
      : undefined
  })
  const items = computed<FieldArrayItem[]>(() => {
    const current = container()
    const meta = current?.arrayMeta
    if (!meta) return []
    return meta.itemIds.map((id, index) => ({ id, nodeId: current.children[index] }))
  })

  return {
    items,
    canAdd: computed(() => container()?.arrayMeta?.canAdd ?? false),
    canRemove: computed(() => container()?.arrayMeta?.canRemove ?? false),
    canReorder: computed(() => container()?.arrayMeta?.canReorder ?? false),
    add: (value) => form().dispatch({
      type: 'InsertItem',
      containerId: nodeId(),
      index: items().length,
      value,
    }),
    remove: (index) => form().dispatch({ type: 'RemoveItem', containerId: nodeId(), index }),
    move: (from, to) => form().dispatch({ type: 'MoveItem', containerId: nodeId(), from, to }),
  }
}

// packages/react/src/hooks/use-field-array.ts
import { useCallback } from 'react'
import type { ContainerNode, NodeId, StableItemId } from '@texaryn/core'
import { useFormContext } from '../context.js'
import { useStore } from './use-store.js'

export interface FieldArrayItem {
  id: StableItemId
  nodeId: NodeId
}

export interface UseFieldArrayReturn {
  items: FieldArrayItem[]
  canAdd: boolean
  canRemove: boolean
  canReorder: boolean
  add(value?: unknown): void
  remove(index: number): void
  move(from: number, to: number): void
}

export function useFieldArray(nodeId: NodeId): UseFieldArrayReturn {
  const runtime = useFormContext()
  const document = useStore(runtime.document)

  const node = document.nodes[nodeId]
  const containerNode = node?.type === 'container' && node.containerType === 'array'
    ? (node as ContainerNode)
    : undefined

  const items: FieldArrayItem[] = containerNode?.arrayMeta
    ? containerNode.arrayMeta.itemIds.map((id, index) => ({
        id,
        nodeId: containerNode.children[index],
      }))
    : []

  const canAdd = containerNode?.arrayMeta?.canAdd ?? false
  const canRemove = containerNode?.arrayMeta?.canRemove ?? false
  const canReorder = containerNode?.arrayMeta?.canReorder ?? false

  const add = useCallback(
    (value?: unknown) => {
      runtime.dispatch({ type: 'InsertItem', containerId: nodeId, index: items.length, value })
    },
    [runtime, nodeId, items.length],
  )

  const remove = useCallback(
    (index: number) => { runtime.dispatch({ type: 'RemoveItem', containerId: nodeId, index }) },
    [runtime, nodeId],
  )

  const move = useCallback(
    (from: number, to: number) => { runtime.dispatch({ type: 'MoveItem', containerId: nodeId, from, to }) },
    [runtime, nodeId],
  )

  return { items, canAdd, canRemove, canReorder, add, remove, move }
}
